Fix wrapping exclusions for VTK 7
VTK has changed semantics of WRAP_EXCLUDE so that files with that property are
no longer ignored by Python wrapping. To explicitly exclude files from Python
wrapping, it's now necessary to set WRAP_EXCLUDE_PYTHON.

This fixes build errors like the following:

    SlicerPathology-build/QuickTCGA/Logic/QuickTCGASegmenterPython.cxx:25:28: error: static_cast from 'vtkObjectBase *' to 'QuickTCGASegmenter *' is not allowed
    ...
    SlicerPathology-build/ShortCutCore/Logic/ShortCutPython.cxx:25:18: error: static_cast from 'vtkObjectBase *' to 'ShortCut *' is not allowed

One such build that shows these errors is:
http://slicer.cdash.org/viewBuildError.php?buildid=860910